pipeline {
    agent any

    tools {
        jdk 'JDK_17'
        maven 'MAVEN3.8.7'
        owasp "Owas-dependency-check-10"
    }

    environment {
        APP_NAME    = "dptweb"
        APP_VERSION = "1.0"
        TOMCAT_HOME = "/opt/tomcat"
        WAR_NAME    = "${APP_NAME}-${APP_VERSION}.war"
        APP_DIR     = "app/Java-Login-App"
    }

    stages {

        stage('Change Detection') {
            steps {
                echo "✅ Source code detected, starting pipeline"
            }
        }

        stage('Validate') {
            steps {
                sh '''
                    cd ${APP_DIR}
                    mvn validate
                    
                '''
            }
        }

        stage('Comlile') {
            steps {
                sh '''
                    cd ${APP_DIR}
                    mvn clean compile -DskipTests
                    
                '''
            }
        }


        stage('Dependency scanning') {
            parallel {
                /* =========================================
                 * 1. CLI OWASP Dependency-Check + Manual Gate
                 * ========================================= */
                 stage('CLI Dependency Audit') {
                    steps {
                        sh """
                            cd ${APP_DIR}

                            mvn org.owasp:dependency-check-maven:check \
                                -DfailOnCVSS=11 \
                                -Dformat=XML
                        """
                        sh """
                            cd ${APP_DIR}

                            CRITICAL=\$(grep -o '<severity>Critical</severity>' target/dependency-check-report.xml | wc -l)
                            HIGH=\$(grep -o '<severity>High</severity>' target/dependency-check-report.xml | wc -l)

                            echo "Critical vulnerabilities: \$CRITICAL"
                            echo "High vulnerabilities: \$HIGH"

                            TOTAL=\$((CRITICAL + HIGH))

                            if [ "\$TOTAL" -gt 1 ]; then
                              echo "❌ More than 1 High/Critical vulnerability found"
                              exit 1
                            else
                              echo "✅ Vulnerability threshold acceptable"
                            fi
                        """
                    }
                 }
                 /* =========================================
                 * 2. Jenkins OWASP Dependency-Check Plugin
                 * ========================================= */
                stage('Jenkins OWASP Plugin Scan') {
                    steps {
                        dependencyCheck additionalArguments: '''
                            --scan .
                            --format XML
                            --prettyPrint
                        ''',
                        odcInstallation: 'Owas-dependency-check-10'

                        dependencyCheckPublisher(
                            pattern: '**/dependency-check-report.xml',
                            failedTotalCritical: 1,
                            stopBuild: true
                        )
                    }
                }
            }
        }

        // stage('Package WAR') {
        //     steps {
        //         sh '''
        //             cd app
        //             mvn package -DskipTests
        //             ls -lh target/*.war
        //         '''
        //     }
        // }

        // stage('Deploy to Tomcat') {
        //     when {
        //         changeset "app/**"
        //     }
        //     steps {
        //         sh '''
        //             sudo rm -rf $TOMCAT_HOME/webapps/$APP_NAME
        //             sudo rm -f  $TOMCAT_HOME/webapps/$APP_NAME.war

        //             sudo cp app/$WAR_FILE $TOMCAT_HOME/webapps/

        //             sudo $TOMCAT_HOME/bin/shutdown.sh || true
        //             sleep 5
        //             sudo $TOMCAT_HOME/bin/startup.sh
        //         '''
        //     }
        // }

        // stage('Health Check') {
        //     when {
        //         changeset "app/**"
        //     }
        //     steps {
        //         sh '''
        //             sleep 15
        //             curl -f http://localhost:8080/$APP_NAME || exit 1
        //         '''
        //     }
        // }

    }

    // post {
    //     success {
    //         echo "✅ App tier deployment successful"
    //     }
    //     failure {
    //         echo "❌ App tier deployment failed"
    //     }
    // }
}
