pipeline {
    agent any

    tools {
        jdk 'JDK_17'
        maven 'MAVEN3.8.7'
        'dependency-check' 'Owas-dependency-check-10'
    }

    environment {
        APP_NAME    = "dptweb"
        APP_VERSION = "1.0"
        TOMCAT_HOME = "/opt/tomcat"
        WAR_NAME    = "${APP_NAME}-${APP_VERSION}.war"
        APP_DIR     = "app/Java-Login-App"
        SPRING_DATASOURCE_URL = 'jdbc:mysql://localhost:3306/dptweb'
        SPRING_DATASOURCE_USERNAME = credentials('SPRING_DATASOURCE_USERNAME')
        SPRING_DATASOURCE_PASSWORD = credentials('SPRING_DATASOURCE_PASSWORD')
        SONAR_SCANNER_HOME = tool 'SonarQube SAST'
    }

    stages {

        stage('Change Detection') {
            steps {
                echo "✅ Source code detected, starting pipeline"
            }
        }

        stage('Validate') {
            steps {
                sh '''
                    cd ${APP_DIR}
                    mvn clean
                    mvn validate
                    
                '''
            }
        }

        stage('ComPile') {
            steps {
                sh '''
                    cd ${APP_DIR}
                    mvn clean compile -DskipTests
                    
                '''
            }
        }


        stage('Dependency scanning') {
            parallel {
                /* =========================================
                 * 1. CLI OWASP Dependency-Check + Manual Gate
                 * ========================================= */
                 
                 stage('CLI Dependency Audit') {
                    steps {
                        sh """
                            cd ${APP_DIR}

                            mvn org.owasp:dependency-check-maven:check \
                                -DautoUpdate=false \
                                -Dformat=ALL
                        """
                        
                        sh """
                            cd ${APP_DIR}

                            CRITICAL=\$(grep -o '<severity>Critical</severity>' target/dependency-check-report.xml | wc -l)
                            HIGH=\$(grep -o '<severity>High</severity>' target/dependency-check-report.xml | wc -l)

                            echo "Critical vulnerabilities: \$CRITICAL"
                            echo "High vulnerabilities: \$HIGH"

                            TOTAL=\$((CRITICAL + HIGH))

                            if [ "\$TOTAL" -gt 1 ]; then
                              echo "❌ More than 1 High/Critical vulnerability found"
                              exit 1
                            else
                              echo "✅ Vulnerability threshold acceptable"
                            fi
                        """
                    }
                 }
                 
                 stage('Jenkins OWASP Plugin Scan') {
                    steps {
                        dependencyCheck additionalArguments: '''
                            -n
                            --scan app/Java-Login-App
                            --out app/Java-Login-App/target/odc-jenkins
                            --format XML
                            --prettyPrint
                        ''',
                        odcInstallation: 'Owas-dependency-check-10'
                        dependencyCheckPublisher(
                            pattern: 'app/Java-Login-App/target/odc-jenkins/dependency-check-report.xml',
                            failedTotalCritical: 1,
                            stopBuild: true
                        )

                        publishHTML([
                            allowMissing: true,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: 'app/Java-Login-App/target',
                            reportFiles: 'dependency-check-report.html',
                            reportName: 'OWASP Dependency-Check (Maven CLI)',
                            reportTitles: 'Dependency-Check Report',
                            useWrapperFileDirectly: true
                        ])

                        
                    }
                 }
            }
        }
        stage("Unit Testing") {
            steps{
                withCredentials([
                    string(credentialsId: 'SPRING_DATASOURCE_USERNAME', variable: 'SPRING_DATASOURCE_USERNAME'),
                    string(credentialsId: 'SPRING_DATASOURCE_PASSWORD', variable: 'SPRING_DATASOURCE_PASSWORD')
                ]) {
                    sh '''
                        cd ${APP_DIR}
                        mvn clean test
                    '''
                    publishHTML([
                            allowMissing: true,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: 'app/Java-Login-App/target/site/jacoco/',
                            reportFiles: 'index.html',
                            reportName: 'Code coverage report',
                            reportTitles: 'Code coverage Report',
                            useWrapperFileDirectly: true
                        ])
                }
            } 
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarQube Analysis') {
                    sh '''
                        cd ${APP_DIR}
                        mvn sonar:sonar \
                          -Dsonar.projectKey=webapplication \
                          -Dsonar.sources=src/main/java \
                          -Dsonar.tests=src/test/java \
                          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                    '''
                }
            }
        }
        

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}
                 